name: Anne Muehlmeier
markdown: redcarpet
highlighter: true
permalink: /portfolio/:caption_header/:photo/ #/:year/:month/:title/
url: http://127.0.0.1:4000/ # http://nadjetey.github.io/GridGallery/
author:
    name: Dan Bender
    twitter: https://twitter.com/thedanbender