name: Anne Muehlmeier
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:title/
url: http://www.annemuehlmeier.com #http://localhost:4000/
author:
    name: Dan Bender
    twitter: https://twitter.com/thedanbender