name: Anne Muehlmeier
markdown: redcarpet
highlighter: true
permalink: /:category/:title #/:year/:month/:title/
url: http://www.annemuehlmeier.com/
author:
    name: Dan Bender
    twitter: https://twitter.com/thedanbender