name: Anne Muehlmeier
# markdown: redcarpet
highlighter: rouge
permalink: /:year/:month/:title/
url: http://annemuehlmeier.com #http://localhost:4000/
author:
    name: Dan Bender
    twitter: https://twitter.com/thedanbender
